ReservationSystem/Models/ApplicationUser.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.IdentityModel;
using Microsoft.AspNetCore.Identity;

namespace ReservationSystem.Models
{
    public class ApplicationUser:IdentityUser
    {
        public string RefreshToken { get; set; }
    }
}

ReservationSystem/Models/ErrorViewModel.cs
using System;

namespace ReservationSystem.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ReservationSystem/Models/Rezervation.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ReservationSystem.Models
{
    public class Rezervation
    {
        
        public int Id { get; set; }
        public string ApplicationUserId { get; set; }
        public ApplicationUser ApplicationUser { get; set; }
        public DateTime Create { get; set; }
        public int PeopleSum { get; set; }
        public string Note { get; set; }
        public bool Confirmed { get; set; }
    }
}

ReservationSystem/Components/LoginViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ReservationSystem.Components
{
    public class LoginViewComponent : ViewComponent
    {

        


    }
}

ReservationSystem/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ReservationSystem.Models;

namespace ReservationSystem.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult Login()
        {
            return View();
        }

        public IActionResult Book()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ReservationSystem/Controllers/Reservation/ReservationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ReservationSystem.Controllers.Reservation.Impl;
using ReservationSystem.Dto;
using ReservationSystem.Models;

namespace ReservationSystem.Controllers.Reservation
{
    [Route("api/[controller]")]
    [ApiController]
    public class ReservationController : ControllerBase
    {
        private IReservationHandler _handler;
        private IEmailSender _sender;
       
        public ReservationController(IReservationHandler handler, IEmailSender sender)
        {
            _handler = handler;
            _sender = sender;

        }

        [Route("book")]
        [HttpPost]
        [Authorize]
        public IActionResult Book(RezDto dto)
        {
            //var accessToken = _httpContextAccessor.HttpContext.Request.Headers["Authorization"];

            var token = HttpContext.User.Identity as ClaimsIdentity;
            var userId = token.Claims.ToList()[0].Value;
            dto.UserId = userId;

            RezDto newDto = _handler.CreateReservation(dto);
            
            if (newDto == null)
                return BadRequest();

            newDto.UserId = null;
            return Ok(newDto);
        }

        [Route("getrez")]
        [HttpGet]
       // [Authorize(Roles = "admin")]
        public IActionResult GetRezervations()
        {
            List<Rezervation> rezervations = _handler.GetRezervations();

            return Ok(rezervations);
        }
        [HttpPut]
        [Route("Potvrdi")]
        [Authorize(Roles ="admin")]
        public IActionResult Potvrdi([FromBody]PotvrdiDto dto)
        {

            var rezultat=_handler.Potvrdi(dto.ReservationId);
            if (rezultat == false)
                return BadRequest("");
            _sender.SendEmail(dto.Username);

            return Ok();
        }



    }
}

ReservationSystem/Controllers/User/UserController.cs
using System;
using System.Collections.Generic;
using System.IdentityModel.Tokens.Jwt;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ReservationSystem.Dto;
using ReservationSystem.Models;


namespace ReservationSystem.Controllers.User
{
    [Route("api/[controller]")]
    [ApiController]

    public class UserController : Controller
    {
        //private IHttpContextAccessor _httpContextAccessor;
        private IUserHandler _handler;
        public UserController( IUserHandler handler)
        {
            _handler = handler;
           // _httpContextAccessor = httpContextAccessor;
        }


        
        [Route("login")]
        [HttpPost]
        public IActionResult Login(LoginDto dto) 
        {


            var token = _handler.Login(dto);
            if (token == null)
                return BadRequest("Prijava nije uspjela");
            
            return Ok(token);
        }

        [Route("refreshToken/{refreshToken}")]
        [HttpGet]
        public IActionResult refreshToken([FromRoute] string refreshToken) 
        {
            var token = _handler.Refresh(refreshToken);
            if (token == null)
            {
                return Unauthorized();
            }

            return Ok(token);
        }


        [Route("register")]
        [HttpPost]
        public IActionResult Register(RegisterDto dto)
        {
            

            RegisterDto newDto = _handler.Register(dto);
            if (newDto == null)
            {
                return BadRequest();
            }
            return Ok(newDto);
        }

        //[Route("GetUsers")]
        //[HttpGet]
        //[Authorize (Roles ="admin")]
        public IActionResult GetUsers()
        {
            List<ApplicationUser> users = _handler.GetUsers();
            

            return Ok(users);
        }
    }
}

ReservationSystem/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ReservationUsingRazor.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

ReservationSystem/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ReservationUsingRazor</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">ReservationUsingRazor</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Register">Register</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - ReservationUsingRazor - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

ReservationSystem/Views/Home/Book.cshtml
@model ReservationSystem.Dto.RezDto


@*<form class="form-horizontal" method="post">
        <input type="datetime-local" class="form-control" name="Datum">
        <button type="submit" class="btn btn-default" style="background-color : cadetblue " asp-controller="Reservation" asp-action="Book">Book</button>
    </form>*@

<form class="form-horizontal" method="post">
    <div class="form-group">
        <label for="datum" class="col-sm-2 control-label">Pick a date</label>
        <div class="col-sm-10">
            <input type="number" class="form-control" name="PeopleSum">
            <input type="datetime-local" class="form-control" name="Create">
            <button type="submit" class="btn btn-default" style="background-color : cadetblue " asp-controller="Reservation" asp-action="Book">Book</button>
        </div>
    </div>


    
</form>

ReservationSystem/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Index";
}


<form class="form-horizontal" method="post">
    <div class="form-group">
        <label for="Name" class="col-sm-2 control-label">Username</label>
        <div class="col-sm-10">
            <input type="text" class="form-control" name="username">
        </div>
    </div>
    <div class="form-group">
        <label for="Email" class="col-sm-2 control-label">Email</label>
        <div class="col-sm-10">
            <input type="text" class="form-control" name="Email">
        </div>
    </div>
    <div class="form-group">
        <label for="password" class="col-sm-2 control-label">Password</label>
        <div class="col-sm-10">
            <input type="password" class="form-control" name="Password">
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-default" style="background-color : cadetblue "  asp-controller="User" asp-action="Register">Register</button>
        </div>
    </div>
</form>

ReservationSystem/Views/Home/Login.cshtml
@page "{login}"
@{ 
        }



    <form class="form-horizontal" method="post">
        <div class="form-group">
            <label for="Name" class="col-sm-2 control-label">Username</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" name="Username">
            </div>
        </div>
        
        <div class="form-group">
            <label for="password" class="col-sm-2 control-label">Password</label>
            <div class="col-sm-10">
                <input type="password" class="form-control" name="Password">
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-default" asp-controller="User" asp-action="Login" >Login</button>
            </div>
        </div>
    </form>

ReservationSystem/Views/Reservation/Book.cshtml
@{
    ViewData["Title"] = "Book";
}

<h1>You've successfully booked your place!! Email will be sent to you with all information shortly!!</h1>

ReservationSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ReservationSystem</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Chewbacca</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    @*<partial name="_LoginPartial" />*@
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="Login"  >Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Book">Book</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - ReservationSystem - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

ReservationSystem/Views/User/Login.cshtml
@{
    ViewData["Title"] = "Login";
}

<h1>You are logged in!!</h1>

ReservationSystem/Views/User/Register.cshtml
@{
    ViewData["Title"] = "Register";
}

<h1>You've been successfully registered!! Proceed to login page</h1>
<a href="~/Home/Login">Login page</a>